/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import com.quante31.weatherapi.gui.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
       App classUnderTest = new App();
       //assert(classUnderTest.main(null));
    }
}
